#!/bin/bash
#
# Build steps to validate the KetoHub Thumbnail Processor.

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

# Delete pyc files from previous builds.
find . -name "*.pyc" -delete

# Run unit tests and calculate code coverage.
coverage run \
  --source processor \
  -m unittest discover

# Check that source has correct formatting.
yapf --diff --recursive --style google ./ --exclude=third_party/*

# Run static analysis for Python bugs/cruft.
pyflakes processor/*.py tests/*.py

# Check docstrings for style consistency.
PYTHONPATH=$PYTHONPATH:$(pwd)/third_party/docstringchecker \
  pylint --reports=n --rcfile=.pylintrc processor tests
